sense_inventory:
  _target_: src.sense_inventories.BabelNetSenseInventory
  inventory_path: data/xl-wsd/inventories/inventory.${oc.env:XL_WSD_LANGUAGE}.txt

callbacks:
  - _target_: src.pl_callbacks.framework_evaluation.XLWSDEvaluationCallback
    raganato_path: data/xl-wsd/evaluation_datasets/dev-${oc.env:XL_WSD_LANGUAGE}/dev-${oc.env:XL_WSD_LANGUAGE}
    framework_dir: data/xl-wsd
    predictors:
      predictor:
        _target_: src.predictors.simple_transformer.SimpleTransformerPredictor
        module: null
        tokenizer: null
        sense_inventory: ${callbacks.sense_inventory}
        sense_vocabulary_path: sense_vocabulary.txt  # todo code quality
        cut_senses: True
        tokens_per_batch: 4096
